#!/bin/bash

echo "[*] Resetting Database..."
mysql -u root -p114514 < dao/init.sql

echo "[*] Registering User..."
python cli.py user register admin admin123

echo "[*] Logging in..."
python cli.py user login admin admin123

CID1=$(python cli.py post create | awk '{print $4}')
echo "[+] Created Post 1 CID: $CID1"

python cli.py post update $CID1 title "Hello MegaCite"
python cli.py post update $CID1 category "Intro"
python cli.py post update $CID1 description "First blog post"
python cli.py post update $CID1 context "# Welcome\n\nThis is the **first** post generated by CLI.\n\nIt supports Markdown!"

CID2=$(python cli.py post create | awk '{print $4}')
echo "[+] Created Post 2 CID: $CID2"

python cli.py post update $CID2 title "Markdown Features"
python cli.py post update $CID2 category "Docs"
python cli.py post update $CID2 context "## List Test\n\n- Feature A\n- Feature B\n\n> Code is poetry."

# python cli.py post migrate https://www.cnblogs.com/swizard/p/19332596

echo "[*] Starting Server on port 8080..."
python cli.py server start 8080